name: Make Release - From remote workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-remote:
    uses: BRDK-GitHub/BrdkLibrariesProject/.github/workflows/release_one_subtree.yml@main
    with:
      artifact_owner: "BRDK-GitHub"
      artifact_repo: "BrdkLibrariesProject"
      artifact_workflow_ref: ".github/workflows/build_BrdkAlarm.yml"   # <-- EDIT
    secrets:
      github-pat-token: ${{ secrets.SERVICE_PAT }}
